baseURL = 'https://gelocraft.dev/'
locale = 'en-us'
title = 'gelocraft.dev'

timezone = "Asia/Manila"

[markup]
    [markup.highlight]
        style = 'catppuccin-latte'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
